import { useEffect, useState } from "react";
import { allocationService, getErrorMessage, roomService, studentService } from "../services/api";
import { useAuth } from "../context/AuthContext";
import { Badge, Empty, ErrorMessage, formatDate, Loading, StatCard } from "../components/UI";

const getGreeting = () => {
  const hour = new Date().getHours();
  if (hour < 12) return "Good morning";
  if (hour < 18) return "Good afternoon";
  return "Good evening";
};

export default function Dashboard() { const { user } = useAuth(); return user.role === "Admin" ? <AdminDashboard /> : <StudentDashboard />; }

function useCampusData() { const [data, setData] = useState({ students: [], rooms: [], allocations: [] }); const [state, setState] = useState({ loading: true, error: "" }); const load = () => { setState({ loading: true, error: "" }); Promise.all([studentService.list(), roomService.list(), allocationService.list()]).then(([students, rooms, allocations]) => setData({ students: students.data, rooms: rooms.data, allocations: allocations.data })).catch((err) => setState({ loading: false, error: getErrorMessage(err) })).finally(() => setState((current) => ({ ...current, loading: false }))); }; useEffect(load, []); return { ...data, ...state, reload: load }; }

function AdminDashboard() { const { students, rooms, allocations, loading, error } = useCampusData(); if (loading) return <Loading text="Loading campus overview..." />; if (error) return <ErrorMessage message={error} />; const active = allocations.filter((item) => item.status === "Active"); const capacity = rooms.reduce((sum, room) => sum + Number(room.Capacity || 0), 0); const occupied = rooms.reduce((sum, room) => sum + Number(room.OccupiedCount || 0), 0); const full = rooms.filter((room) => room.Status === "Full").length; return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">Tuesday, 16 September 2026</span><h2>{getGreeting()}, administrator</h2><p className="muted">Here is the pulse of your residential campus.</p></div><div className="heading-mark">✦</div></div><div className="stat-grid"><StatCard label="Total students" value={students.length} note="Registered residents" /><StatCard label="Room capacity" value={capacity} note={`${occupied} beds currently occupied`} accent="blue" /><StatCard label="Active allocations" value={active.length} note="Live room assignments" accent="green" /><StatCard label="Available beds" value={Math.max(capacity - occupied, 0)} note={`${full} rooms at capacity`} accent="orange" /></div><div className="content-grid"><section className="panel feature-panel"><div className="panel-heading"><div><span className="eyebrow">Live occupancy</span><h3>Rooms at a glance</h3></div><span className="panel-count">{rooms.length} rooms</span></div>{rooms.length ? <div className="room-list">{rooms.slice(0, 6).map((room) => <div className="room-row" key={room._id}><div className="room-icon">{room.Block}</div><div className="room-info"><strong>{room.RoomNo}</strong><small>Block {room.Block} · Floor {room.Floor}</small></div><div className="room-meter"><div><span>{room.OccupiedCount || 0} / {room.Capacity || 0}</span><Badge>{room.Status}</Badge></div><div className="meter"><i style={{ width: `${Math.min((Number(room.OccupiedCount || 0) / Number(room.Capacity || 1)) * 100, 100)}%` }} /></div></div></div>)}</div> : <Empty title="No rooms yet" text="Add rooms to see occupancy here." />}</section><section className="panel accent-panel"><span className="eyebrow">Allocation health</span><h3>{capacity ? Math.round((occupied / capacity) * 100) : 0}%</h3><p>of campus beds are occupied.</p><div className="large-meter"><i style={{ width: `${capacity ? Math.min((occupied / capacity) * 100, 100) : 0}%` }} /></div><div className="accent-stats"><span><b>{occupied}</b>Occupied</span><span><b>{Math.max(capacity - occupied, 0)}</b>Available</span></div></section></div></div>; }

function StudentDashboard() { const { user } = useAuth(); const { students, rooms, allocations, loading, error } = useCampusData(); if (loading) return <Loading text="Loading your residence..." />; if (error) return <ErrorMessage message={error} />; const student = user.student || students.find((item) => item._id === user.student?._id || item.Rollno === user.student?.Rollno); const allocation = allocations.find((item) => item.status === "Active" && (item.studentId?._id === student?._id || item.studentId === student?._id || item.studentName === student?.Name)); const room = rooms.find((item) => item.RoomNo === allocation?.roomNo); const roommates = allocation && student ? allocations.filter((item) => item.status === "Active" && item.roomNo === allocation.roomNo && item.studentName !== student.Name) : []; return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">Resident portal</span><h2>{getGreeting()}, {student?.Name || user.name}</h2><p className="muted">Everything you need to know about your stay, in one view.</p></div></div><div className="student-hero"><div className="student-profile"><div className="profile-avatar">{(student?.Name || user.name).slice(0, 1)}</div><div><span className="eyebrow">Your profile</span><h3>{student?.Name || user.name}</h3><p>{student?.Course || "Course not provided"} · {student?.Campus || "Campus not provided"}</p></div></div><div className="profile-facts"><span><small>Roll number</small><b>{student?.Rollno || "—"}</b></span><span><small>Year</small><b>{student?.Year || "—"}</b></span></div></div>{!allocation ? <div className="panel"><Empty title="No active room allocation" text="Your hostel team has not assigned a room to you yet." /></div> : <div className="content-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Current allocation</span><h3>Room {allocation.roomNo}</h3></div><Badge>{allocation.status}</Badge></div><div className="detail-grid"><span><small>Block</small><b>{room?.Block || "—"}</b></span><span><small>Floor</small><b>{room?.Floor || "—"}</b></span><span><small>Capacity</small><b>{room?.Capacity || "—"}</b></span><span><small>Occupied</small><b>{room?.OccupiedCount ?? "—"}</b></span><span><small>Remaining beds</small><b>{room ? Math.max(room.Capacity - room.OccupiedCount, 0) : "—"}</b></span><span><small>Allocated</small><b>{formatDate(allocation.allocationDate)}</b></span></div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Shared space</span><h3>Roommates</h3></div><span className="panel-count">{roommates.length}</span></div>{roommates.length ? roommates.map((mate) => <div className="mate-row" key={mate.id}><span className="avatar small">{mate.studentName?.slice(0, 1)}</span><span><strong>{mate.studentName}</strong><small>Active resident</small></span></div>) : <Empty title="No roommates" text="You currently have this room to yourself." />}</section></div>}</div>; }
